[Features] Authentication & Authorization
dwarvesf/smithy pull request #35
Opened 2018-08-23 03:48 UTC by neverdiefc

#### Status

READY

#### What's this PR do?

- [x] Reject request without Authenticate header, not valid Authentication header (expired JWT Token, wrong JWT Token, JWT Token not generated from server)
- [x] Reject request from a user with incorrect roles to access endpoints
- [x] Check username and password is valid

2018-08-23 04:10 UTC, hieunmce requested changes

2018-08-23 04:10 UTC, hieunmce commented on backend/auth/auth.go
> +func AuthenticateOnlyAdmin(next http.Handler) http.Handler {
we should have better name for this

2018-08-23 04:10 UTC, hieunmce commented on backend/auth/auth.go
> +func AuthenticateUserAdmin(next http.Handler) http.Handler {
we should have better name for this

2018-08-23 04:10 UTC, hieunmce commented on backend/backend.go
> +func NewUserConfig(r backendConfig.Reader) (*backendConfig.TokenInfo, error) {
we should have better name for this

2018-08-23 04:10 UTC, hieunmce commented on backend/config/config.go
> +	UserConfig              *TokenInfo
we should have better name for this

2018-08-23 04:10 UTC, hieunmce commented on backend/config/config.go
> +func (c *Config) SetUserConfig(userConfig *TokenInfo) *Config {
We should have a consistent in naming (variable should have some thing related with it type or have a appropriate context)

2018-08-23 04:10 UTC, hieunmce commented on backend/endpoints/login.go
> +	admin string = "admin"
we should not make repeat constant have same meaning

2018-08-23 04:10 UTC, hieunmce commented on backend/endpoints/login.go
> +			return nil, errors.New("Login fail")
We should add custom error for this case because in currently it will have status code 500 (internal server error) it will make front-end complain us

2018-08-23 04:10 UTC, hieunmce commented on backend/http/http.go
> +	auth "github.com/dwarvesf/smithy/backend/auth"
we should re-order import

2018-08-23 04:36 UTC, LuanNgoMinh commented on backend/auth/auth.go
> +		pp.Println(err)
yeah!

2018-08-24 05:06 UTC, hieunmce requested changes

2018-08-24 05:06 UTC, hieunmce commented on cmd/backend/main.go
> +
why add space in here

2018-08-24 05:06 UTC, hieunmce commented on example_dashboard_config.yaml
> +    aaa:
we should use array instead

2018-08-24 07:31 UTC, hieunmce approved these changes

2018-08-24 07:32 UTC, merged